### ISSUE TITLE
pom引用

### ISSUE THREAD

**Issue by lee-mz** [Dorae132/easyexcel#2]
哥们，你这包是放在了哪个仓库？我pom根本引用不到。。。
是认真的吗？？？？

**Comment by Dorae132** [comment]
不好意思，这个在我们的私服，有需要的话请自己打个包哈。

**Comment by lee-mz** [comment]
ok，谢了。我以为你放到了公网到maven服务器上。我试试看，谢谢

**Comment by Dorae132** [comment]
好用的话欢迎start😀

**Comment by Dorae132** [comment]
@lee-mz 好用的话欢迎start😀
