### ISSUE TITLE
ExcelProperties能改成建造器模式 这样用来更简单, 

### ISSUE THREAD

**Issue by jikun2008** [Dorae132/easyexcel#5]
ExcelProperties能改成建造器模式 这样用来更简单, 构造函数传递的参数太多了

**Comment by Dorae132** [comment]
不考虑用builder是因为，大多参数都是必传的。
另外builder模式在构造这种对象似乎没有太大优势，除了代码看起来可能舒服一点，但是对于不了解的人来说容易漏掉参数。

**Comment by Dorae132** [comment]
@jikun2008 
不考虑用builder是因为，大多参数都是必传的。
另外builder模式在构造这种对象似乎没有太大优势，除了代码看起来可能舒服一点，但是对于不了解的人来说容易漏掉参数。
