### ISSUE TITLE
大兄弟你这和阿里的easyexcel差距有点大

### ISSUE THREAD

**Issue by hankeqi** [Dorae132/easyexcel#7]
阿里的easyexcel  30W数据 clos = 8113毫秒  默认线程数
Dorae132的easyexcel 30W数据 clos = 14007毫秒 @Dorae132  10个线程数
希望优化 加油！

**Comment by Dorae132** [comment]
1.定位其实不太一样的。包括阿里的excel工具在内，侧重的是excel的读写性能提升，可以说是个读写excel的内核。
2. 但是做这个的目的是屏蔽掉和excel读写相关的操作，同时封装通用的业务场景，使开发更便捷，可以说更侧重excel内核之上的封装。
3. 如果需要，可以自主替换掉内核，实现自己的context即可。
4. 另外目前的并行模式，对于写文件而言，是捞数据与写文件的异步化，对于一次调用而言其实只有两个线程工作；对于读文件而言，是读文件与处理行的异步化，增加线程数只能提升消费行，但是单线程读文件的瓶颈暂时没有解决。如有需要可以考虑替换内核或者考虑并行文件读取；
